kind: Template
apiVersion: v1
template: population-data-loader
metadata:
  name: population-data-loader
objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: ${JOB_NAME}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: ${JOB_NAME}
      spec:
        containers:
          - name: population-data-loader
            image: 172.30.1.1:5000/cpu2019/population-data-loader
            env:
              - name: SERVER
                value: postgresql
              - name: DBNAME
                value: populationDb
              - name: USER
                value: username
              - name: PASSWORD
                value: password
        restartPolicy: OnFailure

parameters:
  - name: JOB_NAME
    from: "jdsl-[a-z0-9]{4}"
    generate: expression
    description: unique name for this job run
